substitutions:
  name: tesla-ble-esp32s3-generic
  friendly_name: Tesla BLE ESP32-S3 Generic
  ble_mac_address: "A1:B2:C3:D4:E5:F6" # !secret ble_mac_address
  tesla_vin: "5YJ30123456789ABC" # !secret tesla_vin
  charging_amps_max: "32"

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: snuffy2.esphome-tesla-ble
    version: "2025.1.3"
  libraries:
    - https://github.com/snuffy2/tesla-ble.git#main

external_components:
  - source: github://snuffy2/esphome-tesla-ble@main
    components: [tesla_ble_vehicle, tesla_ble_listener]

packages:
  base: !include ../packages/base.yml
  device_base: !include ../boards/esp32s3-generic.yml
  client: !include ../packages/client.yml

dashboard_import:
  package_import_url: github://snuffy2/esphome-tesla-ble/tesla-ble-esp32s3-generic.yml@main
  import_full_config: true
#
# Enable this to scan for BLE devices
# tesla_ble_listener:
#   vin: $tesla_vin
