substitutions:
  name: tesla-ble
  friendly_name: Tesla BLE
  ble_mac_address: "A1:B2:C3:D4:E5:F6" # !secret ble_mac_address
  tesla_vin: "5YJ30123456789ABC" # !secret tesla_vin
  charging_amps_max: "32"

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: snuffy2.esphome-tesla-ble
    version: "2025.1.0"
  libraries:
    - https://github.com/snuffy2/tesla-ble.git#main

external_components: !include ../packages/external_components.yml

packages:
  base: !include ../packages/base.yml
  device_base: !include ../boards/m5stack-atoms3.yml
  client: !include ../packages/client.yml

dashboard_import:
  package_import_url: github://snuffy2/esphome-tesla-ble/tesla-ble-m5stack-atoms3.yml
