defaults:
  friendly_name: Tesla BLE
  name: tesla-ble

packages:
  board: !include board.yml
  common: !include common.yml
  project: !include project.yml

safe_mode:

api:
  id: api_server

wifi:
  ap:
    ssid: ${friendly_name} Captive Portal

ota:
  - platform: esphome

logger:
  level: INFO

captive_portal:

improv_serial:
