name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-matrix-list:
    name: Build Matrix File List
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Set Matrix Variable
        id: set-matrix
        run: |
          matrix=$(find . -maxdepth 1 -type f -name 'tesla-ble-*.yml' -print | jq -R -s -c 'split("\n")[:-1]')
          echo "$matrix"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"


  ci:
    name: Checking ${{ matrix.file }}
    needs: build-matrix-list
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(needs.build-matrix-list.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.x
          cache: 'pip'
      - name: Install ESPHome
        run: pip install esphome
      - name: Check ESPHome config
        run: esphome -v config ${{ matrix.file }}
