name: Matrix Test
on:
  pull_request:
  push:
  workflow_dispatch:


jobs:
  build-matrix-list:
    name: Build Matrix File List
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Set Matrix Variable
        id: set-matrix
        run: |
          matrix=$(find . -maxdepth 1 -type f -name 'tesla-ble-*.yml' -print | jq -R -s -r 'split("\n")[:-1] | join("\n")')
          echo "${matrix}"
          echo -e "matrix<<EOF\n$matrix\nEOF" >> "$GITHUB_OUTPUT"

  test-matrix-list:
    name: Test Matrix
    runs-on: ubuntu-latest
    needs: build-matrix-list
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: List all files
        run: echo ${{ needs.build-matrix-list.outputs.matrix }}

  build:
    name: Build Manifest & Compile Firmwares
    uses: esphome/workflows/.github/workflows/build.yml@main
    needs: build-matrix-list
    with:
      # Filenames of the config, newline separated (required):
      files: |
        ${{ needs.build-matrix-list.outputs.matrix }}
      # Version of ESPHome to build with (default: latest)
      # esphome-version: latest
      # Summary of the release
      # release-summary:
      # URL to the release notes
      # release-url:
      # Version of the release
      # release-version: latest
      # Combine all files into a single manifest under this name
      combined-name: tesla-ble
