name: Release Process
on:
  pull_request:
  push:
  workflow_dispatch:


jobs:
  debug:
    name: Debug info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Debug Variables
        run: |
            echo "github.event_name: ${{ github.event_name }}"
            echo "github.ref_name: ${{ github.ref_name }}"
            echo "github.event.repository.default_branch: ${{ github.event.repository.default_branch }}"

  build-matrix-list:
    name: Build Matrix File List
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Set Matrix Variable
        id: set-matrix
        run: |
          matrix=$(find . -maxdepth 1 -type f -name 'tesla-ble-*.yml' -print | jq -R -s -c 'split("\n")[:-1] | join("\n")')
          echo "$matrix"
          echo -e "matrix<<EOF\n$matrix\nEOF" >> "$GITHUB_OUTPUT"

  build:
    name: Test Matrix
    runs-on: ubuntu-latest
    needs: build-matrix-list
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: List all files
        run: echo ${{ needs.build-matrix-list.outputs.matrix }}
